### ISSUE TITLE
WISP EPC를 읽을 수 없습니다

### ISSUE THREAD

**Issue by Wangshuai8156** [SpiritFlag/Gen2-UHF-RFID-Reader-with-WISP#25]
링크에 따라 WISP5와 USRP N210의 코드를 각각 다운로드했는데 WISP5의 EPC를 읽을 수 없습니다. USRP 코드 매개 변수를 변경해야합니까? 그런 다음 WISP 프로토콜에 따라 USRP 매개 변수를 변경했지만 여전히 EPC를 읽을 수 없습니다. 아래 그림은 수정 된 매개 변수를 보여줍니다. 이 과정에서 주목할만한 것이 있습니까?
![image](https://user-images.githubusercontent.com/42960991/98125966-fe748c00-1eef-11eb-9865-a59acc9d2052.png)

**Comment by SpiritFlag** [comment]
안녕하세요. 저의 코드에 관심을 갖고 글을 남겨주셔서 감사합니다.

제가 이 repository를 만들 때 원작자의 repository를 clone하지 않은 문제가 있어서(당시에는 제가 github 사용이 서툴었습니다), 현재 작업은 새로운 repository에서 진행되고 있습니다.

아래 링크의 repository를 방문하셔서 최신 release(1.3.0)를 사용해보세요.
https://github.com/SpiritFlag/Gen2-UHF-RFID-Reader/releases/tag/1.3.0

답변이 늦어져서 죄송하고, 추가적인 문의사항이 있으면 새로운 repository에서 남겨주세요.

감사합니다.

---

Hello. Thank you for your interest in my code and writing.

When I made this repository, there was a problem that I didn't clone the original repository (I wasn't good at using github at the time), so the current work is going on in the new repository.

Visit the repository at the link below to try the latest release (1.3.0).
https://github.com/SpiritFlag/Gen2-UHF-RFID-Reader/releases/tag/1.3.0

I'm sorry for the late reply, and if you have any additional questions, please leave them in the new repository.

Thank you.
